### PR TITLE
add Mobile Power Station

### PR DESCRIPTION
**Pull request by pkb-pmj**
Yeah, we're aware it's somewhat similar to #24 and #13 and we're open to collaboration - these 3 projects together could make a nice power system 😃 We're mostly interested in the making a solid, functional power supply part.

### CODE REVIEW

**Comment by SerenityUX** [comment]
yk... having two power banks isn't a bad idea! your approach seems pretty different from the other team :)

**Comment by SerenityUX** [comment]
lgtm! Charlie, wdyt?

**Comment by 24c02** [comment]
i might be a little iffy on the logistics of the batteries, but i'm inclined to say go for it!

**Comment by darth-taco-tmp** [comment]
@24c02 
We know about battery size limits we can take to the plane, today we modified our project a little bit. I decided to switch from big prismatic LiFePO4 cells to 21700 Li-ion ones (mainly because i couldn't find any place where we would be able to buy these besides aliexpress,  where shipping time is about 3 months) and our powerbank will be build from three 138Wh modules. According to airlines website if we request permission we can take batteries up to 160Wh so we should be able to take these.
At least I hope so :)

**Pull request merged**
