### PR TITLE
Add People With Us to main

### PR DESCRIPTION
**Pull request by Swamstick911**

### CODE REVIEW

**Comment by Swamstick911** [comment]
Please merge this PR!

**Comment by AverseABFun** [comment]
oh gosh the name lol
(btw-not an organizer, just love the implication we are just taking People With Us on the trail lol)

**Comment by AverseABFun** [comment]
Oh and then also you need to rename the file to have the `.md` file extension and again I am not a organizer

**Comment by Swamstick911** [comment]
Ok, I'll do that and yeah the name is funny 😂

**Comment by Swamstick911** [comment]
Should I do it right now or after it merges ?

**Comment by AverseABFun** [comment]
Great!

**Comment by AverseABFun** [comment]
Now, because you'd have to make another PR if you wait until after it
merges.

**Comment by Swamstick911** [comment]
Okk just doing it

**Comment by Swamstick911** [comment]
just done it @AverseABFun

**Comment by AverseABFun** [comment]
sounds good!

**Comment by SerenityUX** [comment]
I wonder if there is a possibility to team up with: https://github.com/hackclub/the-trail/pull/9

**Comment by Swamstick911** [comment]
Oh yeah actually we can.. I have to talk to him

**Comment by Swamstick911** [comment]
Hey @SerenityUX just teamed up with him!

**Comment by 24c02** [comment]
@Swamstick911 @ktshacx should i merge this one and close the other, or vice versa?

**Comment by ktshacx** [comment]
@24c02 @Swamstick911  Vice versa would be better, as i have mentioned all the usecased and description of the project properly and also updated the teammates

**Comment by Swamstick911** [comment]
@ktshacx what about design have you updated?

and yes you should merge @ktshacx 's PR!

**Pull request closed without merging**
