### PR TITLE
Add Movement Detector

### PR DESCRIPTION
**Pull request by CodeWithShreyans**

### CODE REVIEW

**Comment by AverseABFun** [comment]
Not an organizer, but I don't think an accelerometer would work here. It might be better to use an ultrasonic sensor or even a tripwire.

**Comment by CodeWithShreyans** [comment]
could test out the accelerometer, then add or switch to the other options if it doesn't.

**Comment by AverseABFun** [comment]
No, like a accelerometer would have to be attached to every single threat that could come through for that to work, which is unreasonable.

**Comment by CodeWithShreyans** [comment]
no like they would be attached to the floor in a circle around the camp and detect vibrations above a certain threshold.

**Comment by AverseABFun** [comment]
You'd need some REALLY precise accelerometers for that, but I suppose it could work. Although what about someone just walking around in the night or rolling over or something?

**Comment by CodeWithShreyans** [comment]
I made a gas detector recently, and just like it this would need calibration through testing, could walk near it and roll near it and everything and read the data to gauge a threshold

**Comment by SerenityUX** [comment]
You should team up with https://github.com/hackclub/the-trail/pull/16

**Pull request closed without merging**
