### PR TITLE
Create memory-bank

### PR DESCRIPTION
**Pull request by Papolele**

### CODE REVIEW

**Comment by AverseABFun** [comment]
Hey, not an organizer but you need to rename the file to have the `.md` file extension.

**Comment by SerenityUX** [comment]
love it! I think there may be a bit of feature creep, but we ABSOLUTELY NEED a battery bank and this could solve a lot of our problems (PLUS BE SOMETHING SUPER FUN!)

pls lean into the battery bank that isn't lifeless elements. so cool.

**Comment by 24c02** [comment]
agree with Thomas here – let's make sure we get the battery bank part right first and then see what cool features we can add

**Comment by Papolele** [comment]
Absolutely!

**Pull request merged**
